export const API_PATHS = {
  AUTH: {
    LOGIN: '/auth/oidc/login',
    TOKEN: '/login',
    REFRESH: '/auth/oidc/refresh',
    LOGOUT: '/auth/oidc/logout',
    ME: '/auth/me',
  },
  DASHBOARD: '/v1/dashboard',
  ENVIRONMENTS: '/v1/environments',
  ENVIRONMENT: (id: string) => `/v1/environments/${id}`,
  ENVIRONMENT_SYNC: (id: string) => `/v1/environments/${id}/sync`,
  ENVIRONMENT_WORKLOADS: (id: string) => `/v1/environments/${id}/workloads`,
  WORKLOADS: '/workloads',
  WORKLOAD: (id: string) => `/workloads/${id}`,
  USERS: '/v1/users',
  USER: (id: string) => `/v1/users/${id}`,
  TEAMS: '/v1/teams',
  TEAM: (id: string) => `/v1/teams/${id}`,
  ROLES: '/v1/roles',
  ROLE: (id: string) => `/v1/roles/${id}`,
  AUDIT_LOGS: '/v1/audit-logs',
  API_KEYS: '/v1/api-keys',
  API_KEY: (id: string) => `/v1/api-keys/${id}`,
  TEMPLATES: '/v1/templates',
  TEMPLATE: (id: string) => `/v1/templates/${id}`,
  TEMPLATE_VERSIONS: (templateId: string) => `/v1/templates/${templateId}/versions`,
  TEMPLATE_VERSION: (templateId: string, versionId: string) => `/v1/templates/${templateId}/versions/${versionId}`,
  TEMPLATE_VERSION_PARAMETERS: (templateId: string, versionId: string) => `/v1/templates/${templateId}/versions/${versionId}/parameters`,
  TEMPLATE_VERSION_RESOURCES: (templateId: string, versionId: string) => `/v1/templates/${templateId}/versions/${versionId}/resources`,
  TEMPLATE_VERSION_VALIDATE: (templateId: string, versionId: string) => `/v1/templates/${templateId}/versions/${versionId}/validate`,
  DELIVERY_TARGETS: '/v1/delivery-targets',
  DELIVERY_TARGET: (id: string) => `/v1/delivery-targets/${id}`,
} as const;

export const QUERY_KEYS = {
  auth: ['auth'] as const,
  dashboard: ['dashboard'] as const,
  environments: ['environments'] as const,
  environmentList: (query?: unknown) => ['environments', 'list', query ?? {}] as const,
  environment: (id: string) => ['environments', 'detail', id] as const,
  environmentWorkloads: (id: string) => ['environments', 'workloads', id] as const,
  adminUsers: ['admin', 'users'] as const,
  adminTeams: ['admin', 'teams'] as const,
  adminRoles: ['admin', 'roles'] as const,
  auditLogs: ['admin', 'audit-logs'] as const,
  apiKeys: ['settings', 'api-keys'] as const,
  templates: ['templates'] as const,
  templateList: (query?: unknown) => ['templates', 'list', query ?? {}] as const,
  template: (id: string) => ['templates', 'detail', id] as const,
  templateVersions: (templateId: string) => ['templates', 'versions', templateId] as const,
  templateVersion: (templateId: string, versionId: string) => ['templates', 'versions', templateId, versionId] as const,
  deliveryTargets: ['delivery-targets'] as const,
  deliveryTargetList: (query?: unknown) => ['delivery-targets', 'list', query ?? {}] as const,
  deliveryTarget: (id: string) => ['delivery-targets', 'detail', id] as const,
} as const;
